import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Feed } from "src/components/feed";
import { UnauthHero } from "src/components/UnauthHero";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>Loading...</div>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? <Feed /> : <UnauthHero />}
    </>
  );
};

export default Home;
